### ISSUE TITLE
Sugerencia: Corregir errores de ortografía

### ISSUE THREAD

**Issue by edme88** [agustindt/Proyecto2023-DiTomaso-Carbel#3]
En el mockup:
* gráfico
* función
* Elija
![imagen](https://github.com/agustindt/Proyecto2023-DiTomaso-Carbel/assets/8345007/37bdf97f-e875-423d-9919-01c5c6058cab)

En el código:
https://github.com/agustindt/Proyecto2023-DiTomaso-Carbel/blob/ff25f96199ede7583fea1b1122dca097b93b6742/index.html#L29

https://github.com/agustindt/Proyecto2023-DiTomaso-Carbel/blob/ff25f96199ede7583fea1b1122dca097b93b6742/index.html#L51

**Comment by agustindt** [comment]
Ya se han corregido los errores ortograficos cometidos
